#!/usr/bin/env bash

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"

# Default output: book.md in the project root.
OUT="${1:-$ROOT_DIR/book.md}"

cat_file() {
	local path="$1"
	if [[ ! -f "$path" ]]; then
		echo "Missing file: $path" >&2
		exit 1
	fi
	# Ensure concatenated files don't glue together when a source file lacks a trailing newline.
	printf '\n'
	cat "$path"
	printf '\n'
}

{
	echo "<!-- Generated by scripts/bundle-for-print.sh on $(date -Iseconds) -->"
	cat <<'CSS'
<style>

.anchorjs-link { display: none !important; }

.markdown-body > h1:first-of-type { display: none !important; }

/* Match the proven test pattern: make break markers real block elements even on screen. */
.page-break,
.page-break-left {
	display: block;
	height: 0;
}

@media print {
	.page-break {
		break-before: right !important;
		page-break-before: right !important;
	}

	.page-break-left {
		break-before: left !important;
		page-break-before: left !important;
	}

	/* Keep headings with their first paragraph (same as tests) */
	h1, h2, h3 { break-after: avoid-page; }

}
</style>
CSS

	# Front matter
	cat_file "$DOCS_DIR/00-frontmatter/00-cover.md"
	cat_file "$DOCS_DIR/00-frontmatter/01-half-title.md"
	cat_file "$DOCS_DIR/00-frontmatter/02-frontispiece.md"
	cat_file "$DOCS_DIR/00-frontmatter/03-title.md"
	cat_file "$DOCS_DIR/00-frontmatter/04-colophon.md"
	cat_file "$DOCS_DIR/00-frontmatter/05-dedication.md"
	cat_file "$DOCS_DIR/00-frontmatter/06-epigraph.md"
	cat_file "$DOCS_DIR/00-frontmatter/07-foreword.md"
	cat_file "$DOCS_DIR/00-frontmatter/08-preface.md"
	cat_file "$DOCS_DIR/00-frontmatter/09-contents.md"
	cat_file "$DOCS_DIR/00-frontmatter/10-introduction.md"

	# Part I
	cat_file "$DOCS_DIR/01-parts/i/00-part-i-the-coming-disruptions.md"
	cat_file "$DOCS_DIR/01-parts/i/01-income-displacement-at-scale.md"
	cat_file "$DOCS_DIR/01-parts/i/02-demand-collapse-and-the-capitalism-paradox.md"
	cat_file "$DOCS_DIR/01-parts/i/03-gatekeeping-as-the-default-failure-mode.md"
	cat_file "$DOCS_DIR/01-parts/i/04-the-geopolitical-arms-race.md"

	# Part II
	cat_file "$DOCS_DIR/01-parts/ii/00-part-ii-dystopias-to-avoid.md"
	cat_file "$DOCS_DIR/01-parts/ii/05-the-welfare-society.md"
	cat_file "$DOCS_DIR/01-parts/ii/06-corporate-ai-feudalism.md"
	cat_file "$DOCS_DIR/01-parts/ii/07-bureaucratic-technocracy.md"
	cat_file "$DOCS_DIR/01-parts/ii/08-epistemic-collapse.md"

	# Part III
	cat_file "$DOCS_DIR/01-parts/iii/00-part-iii-epistemic-stewards.md"
	cat_file "$DOCS_DIR/01-parts/iii/09-reframing-human-value-in-an-agi-world.md"
	cat_file "$DOCS_DIR/01-parts/iii/10-expertise-as-first-class-economic-role.md"

	# Part IV
	cat_file "$DOCS_DIR/01-parts/iv/00-part-iv-architectural-solutions.md"
	cat_file "$DOCS_DIR/01-parts/iv/11-federated-ai-as-structural-antidote-to-gatekeeping.md"
	cat_file "$DOCS_DIR/01-parts/iv/12-federated-mix-of-experts-as-plural-intelligence-fabric.md"
	cat_file "$DOCS_DIR/01-parts/iv/13-domains-of-specialization.md"

	# Part V
	cat_file "$DOCS_DIR/01-parts/v/00-part-v-incentives-and-economics.md"
	cat_file "$DOCS_DIR/01-parts/v/14-funding-expertise-without-welfare.md"
	cat_file "$DOCS_DIR/01-parts/v/15-preventing-the-new-expert-aristocracy.md"
	cat_file "$DOCS_DIR/01-parts/v/16-new-capitalism.md"

	# Part VI
	cat_file "$DOCS_DIR/01-parts/vi/00-part-vi-decentralized-governance.md"
	cat_file "$DOCS_DIR/01-parts/vi/17-rules-of-the-road-not-ownership.md"
	cat_file "$DOCS_DIR/01-parts/vi/18-safety-trust-and-accountability.md"

	# Part VII
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/00-part-vii-transition-pain-and-compromise.md"
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/19-inevitable-growing-pains.md"
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/20-a-society-worth-keeping.md"
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/21-choosing-participation-over-comfort.md"

	# Back matter (excluding back cover)
	cat_file "$DOCS_DIR/02-backmatter/01-bibliography.md"
	cat_file "$DOCS_DIR/02-backmatter/02-index.md"
	cat_file "$DOCS_DIR/02-backmatter/03-acknowledgements.md"
} > "$OUT"

echo "Wrote bundled markdown to: $OUT" >&2

