#!/usr/bin/env bash

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"

# Default output: book.md in the project root.
OUT="${1:-$ROOT_DIR/book.md}"

page_break() {
	echo
	# Use an anchor as a page-break marker (no divs).
	echo '<a class="page-break" aria-hidden="true"></a>'
	echo
}

verso_black_page() {
	echo
	# Explicit black verso page marker (no divs).
	echo '<a class="verso-black" aria-hidden="true"></a>'
	echo
}

verso_blank_page() {
	echo
	# Explicit blank page marker (no divs).
	echo '<a class="verso-blank" aria-hidden="true"></a>'
	echo
}

cat_file() {
	local path="$1"
	if [[ ! -f "$path" ]]; then
		echo "Missing file: $path" >&2
		exit 1
	fi
	cat "$path"
}

{
	echo "<!-- Generated by scripts/bundle-for-print.sh on $(date -Iseconds) -->"
	cat <<'CSS'
<style>
/* Hide GitHub Pages' injected heading permalink anchors (AnchorJS). */
.anchorjs-link {
	display: none !important;
}

/* Hide the theme's repo-title header that appears above the book content. */
.markdown-body > h1:first-of-type {
	display: none !important;
}

/* These markers are only meaningful for printing; hide them on screen. */
a.page-break,
a.verso-black,
a.verso-blank {
	display: none !important;
}

@media print {
	/* Prefer recto starts when supported; fall back to plain page breaks. */
	a.part,
	a.chapter {
		display: block;
		break-before: right;
		page-break-before: always;
	}

	/* Explicit black verso pages between major sections. */
	a.verso-black {
		display: block;
		break-before: page;
		break-after: page;
		page-break-before: always;
		page-break-after: always;
		background: #000;
		width: 100%;
		min-height: 100vh;
	}

	/* Explicit blank pages between sections (useful to force next section onto recto). */
	a.verso-blank {
		display: block;
		break-before: page;
		break-after: page;
		page-break-before: always;
		page-break-after: always;
		background: #fff;
		width: 100%;
		min-height: 100vh;
	}

	/* Utility marker inserted between concatenated files. */
	a.page-break {
		break-after: page;
		page-break-after: always;
		display: block;
		height: 0;
	}
}
</style>
CSS

	# Front matter
	cat_file "$DOCS_DIR/00-frontmatter/00-cover.md"
	verso_black_page
	cat_file "$DOCS_DIR/00-frontmatter/01-half-title.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/02-frontispiece.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/03-title.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/04-colophon.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/05-dedication.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/06-epigraph.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/07-foreword.md"
	verso_black_page
	cat_file "$DOCS_DIR/00-frontmatter/08-preface.md"
	verso_blank_page
	cat_file "$DOCS_DIR/00-frontmatter/09-contents.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/10-introduction.md"

	# Part I
	verso_black_page
	cat_file "$DOCS_DIR/01-parts/i/00-part-i-the-coming-disruptions.md"
	cat_file "$DOCS_DIR/01-parts/i/01-income-displacement-at-scale.md"
	cat_file "$DOCS_DIR/01-parts/i/02-demand-collapse-and-the-capitalism-paradox.md"
	cat_file "$DOCS_DIR/01-parts/i/03-gatekeeping-as-the-default-failure-mode.md"
	cat_file "$DOCS_DIR/01-parts/i/04-the-geopolitical-arms-race.md"

	# Part II
	cat_file "$DOCS_DIR/01-parts/ii/00-part-ii-dystopias-to-avoid.md"
	cat_file "$DOCS_DIR/01-parts/ii/05-the-welfare-society.md"
	cat_file "$DOCS_DIR/01-parts/ii/06-corporate-ai-feudalism.md"
	cat_file "$DOCS_DIR/01-parts/ii/07-bureaucratic-technocracy.md"
	cat_file "$DOCS_DIR/01-parts/ii/08-epistemic-collapse.md"

	# Part III
	cat_file "$DOCS_DIR/01-parts/iii/00-part-iii-epistemic-stewards.md"
	cat_file "$DOCS_DIR/01-parts/iii/09-reframing-human-value-in-an-agi-world.md"
	cat_file "$DOCS_DIR/01-parts/iii/10-expertise-as-first-class-economic-role.md"

	# Part IV
	cat_file "$DOCS_DIR/01-parts/iv/00-part-iv-architectural-solutions.md"
	cat_file "$DOCS_DIR/01-parts/iv/11-federated-ai-as-structural-antidote-to-gatekeeping.md"
	cat_file "$DOCS_DIR/01-parts/iv/12-federated-mix-of-experts-as-plural-intelligence-fabric.md"
	cat_file "$DOCS_DIR/01-parts/iv/13-domains-of-specialization.md"

	# Part V
	cat_file "$DOCS_DIR/01-parts/v/00-part-v-incentives-and-economics.md"
	cat_file "$DOCS_DIR/01-parts/v/14-funding-expertise-without-welfare.md"
	cat_file "$DOCS_DIR/01-parts/v/15-preventing-the-new-expert-aristocracy.md"
	cat_file "$DOCS_DIR/01-parts/v/16-new-capitalism.md"

	# Part VI
	cat_file "$DOCS_DIR/01-parts/vi/00-part-vi-decentralized-governance.md"
	cat_file "$DOCS_DIR/01-parts/vi/17-rules-of-the-road-not-ownership.md"
	cat_file "$DOCS_DIR/01-parts/vi/18-safety-trust-and-accountability.md"

	# Part VII
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/00-part-vii-transition-pain-and-compromise.md"
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/19-inevitable-growing-pains.md"
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/20-a-society-worth-keeping.md"
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/21-choosing-participation-over-comfort.md"

	# Back matter (excluding back cover)
	page_break
	cat_file "$DOCS_DIR/02-backmatter/01-bibliography.md"
	page_break
	cat_file "$DOCS_DIR/02-backmatter/02-index.md"
	page_break
	cat_file "$DOCS_DIR/02-backmatter/03-acknowledgements.md"
} > "$OUT"

echo "Wrote bundled markdown to: $OUT" >&2

