#!/usr/bin/env bash

set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"

# Default output: book.md in the project root.
OUT="${1:-$ROOT_DIR/book.md}"

page_break() {
	echo
	echo '<div class="page-break"></div>'
	echo
}

cat_file() {
	local path="$1"
	if [[ ! -f "$path" ]]; then
		echo "Missing file: $path" >&2
		exit 1
	fi
	cat "$path"
}

{
	echo "<!-- Generated by scripts/bundle-for-print.sh on $(date -Iseconds) -->"
	cat <<'CSS'
<style>
@media print {
	/* Prefer recto starts when supported; fall back to plain page breaks. */
	a.part,
	a.chapter {
		display: block;
		break-before: right;
		page-break-before: always;
	}

	/* Utility marker inserted between concatenated files. */
	.page-break {
		break-after: page;
		page-break-after: always;
	}
}
</style>
CSS

	# Front matter
	cat_file "$DOCS_DIR/00-frontmatter/00-cover.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/01-half-title.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/02-frontispiece.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/03-title.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/04-colophon.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/05-dedication.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/06-epigraph.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/07-foreword.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/08-preface.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/09-contents.md"
	page_break
	cat_file "$DOCS_DIR/00-frontmatter/10-introduction.md"

	# Part I
	page_break
	cat_file "$DOCS_DIR/01-parts/i/00-part-i-the-coming-disruptions.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/i/01-income-displacement-at-scale.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/i/02-demand-collapse-and-the-capitalism-paradox.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/i/03-gatekeeping-as-the-default-failure-mode.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/i/04-the-geopolitical-arms-race.md"

	# Part II
	page_break
	cat_file "$DOCS_DIR/01-parts/ii/00-part-ii-dystopias-to-avoid.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/ii/05-the-welfare-society.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/ii/06-corporate-ai-feudalism.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/ii/07-bureaucratic-technocracy.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/ii/08-epistemic-collapse.md"

	# Part III
	page_break
	cat_file "$DOCS_DIR/01-parts/iii/00-part-iii-epistemic-stewards.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/iii/09-reframing-human-value-in-an-agi-world.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/iii/10-expertise-as-first-class-economic-role.md"

	# Part IV
	page_break
	cat_file "$DOCS_DIR/01-parts/iv/00-part-iv-architectural-solutions.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/iv/11-federated-ai-as-structural-antidote-to-gatekeeping.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/iv/12-federated-mix-of-experts-as-plural-intelligence-fabric.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/iv/13-domains-of-specialization.md"

	# Part V
	page_break
	cat_file "$DOCS_DIR/01-parts/v/00-part-v-incentives-and-economics.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/v/14-funding-expertise-without-welfare.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/v/15-preventing-the-new-expert-aristocracy.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/v/16-new-capitalism.md"

	# Part VI
	page_break
	cat_file "$DOCS_DIR/01-parts/vi/00-part-vi-decentralized-governance.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/vi/17-rules-of-the-road-not-ownership.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/vi/18-safety-trust-and-accountability.md"

	# Part VII
	page_break
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/00-part-vii-transition-pain-and-compromise.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/19-inevitable-growing-pains.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/20-a-society-worth-keeping.md"
	page_break
	cat_file "$DOCS_DIR/01-parts/vii-transition-pain-and-compromise/21-choosing-participation-over-comfort.md"

	# Back matter (excluding back cover)
	page_break
	cat_file "$DOCS_DIR/02-backmatter/01-bibliography.md"
	page_break
	cat_file "$DOCS_DIR/02-backmatter/02-index.md"
	page_break
	cat_file "$DOCS_DIR/02-backmatter/03-acknowledgements.md"
} > "$OUT"

echo "Wrote bundled markdown to: $OUT" >&2

